//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondFactorAuthenticator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecondFactorAuthenticator.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication based on user-hostname association.
        /// </summary>
        internal static string ADAPTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("ADAPTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check of the association user - hostname.
        /// </summary>
        internal static string PAGE_TITLE {
            get {
                return ResourceManager.GetString("PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You have been authenticated.&lt;br/&gt;
        ///You can continue to your application.&lt;/p&gt;
        ///
        ///&lt;form method=&quot;post&quot; id=&quot;loginForm&quot; autocomplete=&quot;off&quot;&gt;
        ///&lt;input id=&quot;context&quot; type=&quot;hidden&quot; name=&quot;Context&quot; value=&quot;%Context%&quot;/&gt;
        ///&lt;input id=&quot;authMethod&quot; type=&quot;hidden&quot; name=&quot;AuthMethod&quot; value=&quot;%AuthMethod%&quot;/&gt;
        ///&lt;input id=&quot;continueButton&quot; type=&quot;submit&quot; name=&quot;Continue&quot; value=&quot;Continue&quot; /&gt;
        ///&lt;/form&gt;
        ///&lt;script&gt;
        ///window.onload = function(){
        ///  document.forms[&apos;loginForm&apos;].submit()
        ///}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string PageHtmlForm {
            get {
                return ResourceManager.GetString("PageHtmlForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;messageArea&quot;&gt;
        ///    &lt;p&gt;You have not been granted access to this application.&lt;/p&gt;
        ///	&lt;p&gt;The message returned from server is:&lt;br/&gt;
        ///	&lt;i&gt;{0}&lt;/i&gt;
        ///	&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string PageHtmlMessage {
            get {
                return ResourceManager.GetString("PageHtmlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported database type in configuration..
        /// </summary>
        internal static string UNSUPPORTED_DB {
            get {
                return ResourceManager.GetString("UNSUPPORTED_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user in database..
        /// </summary>
        internal static string USER_UNKNOWN {
            get {
                return ResourceManager.GetString("USER_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User trying to access from client not registerd into database..
        /// </summary>
        internal static string USER_UNREGISTERED {
            get {
                return ResourceManager.GetString("USER_UNREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong database connection string in configuration..
        /// </summary>
        internal static string WRONG_DB {
            get {
                return ResourceManager.GetString("WRONG_DB", resourceCulture);
            }
        }
    }
}
